service: micro-customer-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    DATABASE_URL: ${ssm:/database-url-${opt:stage, 'dev'}}
    JWT_SECRET: ${ssm:/jwt-secret-${opt:stage, 'dev'}}
    S3_BUCKET_NAME: micro-uploaded-files-${opt:stage, 'dev'}
    RECAPTHA_PRIVATE_KEY: ${ssm:/recaptcha-private-key-${opt:stage, 'dev'}}

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api-${opt:stage, 'dev'}.abhishek.pl
    basePath: customer
    stage: ${opt:stage, 'dev'}
    createRoute53Record: false

  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - aws-sdk
    target: node14
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

package:
  individually: true
  exclude:
    - "*"
    - '.*/**'
    - CHANGELOG/**
    - ".build/**"
    - ".output/**"
    - infrastructure/**
    - node_modules/**
    - scripts/**
    - src/**
    - tests/**
  include:
    - src/**/*.ts
    - package.json
    - '!src/**/__tests__/**'

functions:
  health: ${file(./src/handlers/health/config.yml):health}
  customer_get: ${file(./src/handlers/customer/get/config.yml):get}
  custome_list: ${file(./src/handlers/customer/list/config.yml):list}
  customer_create: ${file(./src/handlers/customer/create/config.yml):create}
  customer_update: ${file(./src/handlers/customer/update/config.yml):update}
