name: Deploy Service to Prod
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Semantic Release
        uses: ./.github/actions/release
        env:
          GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v1
        with:
          branch: master

      - name: Deploy Service to AWS Lambda
        uses: ./.github/actions/deploy
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
        with:
          env: prod
